<a href="https://colab.research.google.com/github/chani723/2020-C-code/blob/master/01_tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 1.x

In [ ]:
#텐서플로 1.0 버전 선택
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 1.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

In [ ]:
import tensorflow as tf

hello = tf.constant('Hello World!')

sess = tf.Session()
print(sess.run(hello))
sess.close()

In [ ]:
a = 10
b = 10
print(tf.add(a, b))

sess = tf.Session()
print(sess.run(tf.add(a, b)))
sess.close()

In [ ]:
%tensorflow_version 2.x

# 메뉴, 런타임 | 런타임 다시 시작

단축키 : ctrl+M

In [1]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [2]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b)

tf.Tensor(8, shape=(), dtype=int32)


In [3]:
c = tf.constant('Hello, world!')
print(c)
print(c.numpy())

tf.Tensor(b'Hello, world!', shape=(), dtype=string)
b'Hello, world!'


In [4]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
a.shape

TensorShape([])

In [6]:
a.dtype

tf.int32

In [7]:
a.numpy()

3

In [8]:
b = tf.constant(3.)
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [9]:
b.shape

TensorShape([])

In [10]:
b.dtype

tf.float32

In [11]:
b.numpy()

3.0

# Tensor

In [12]:
a = tf.constant([1,2,3])
a.shape

TensorShape([3])

In [13]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
a.shape

TensorShape([2, 3])

In [14]:
a = tf.constant([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
a.shape

TensorShape([2, 2, 3])

In [15]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

# tf.cond

In [16]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10))

print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


In [17]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x, y), f1, f2)

r.numpy()

34

In [18]:
# 1차원 배열 텐서
t = tf.constant([1, 2, 3])
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [19]:
x = tf.constant([1, 2, 3])
y = tf.constant([5, 6, 7])

print((x+y).numpy())

[ 6  8 10]


In [20]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
print(a.numpy())

d = a * b + c

print(d)
print(d.numpy())

[5.]
tf.Tensor([52.], shape=(1,), dtype=float32)
[52.]


In [21]:
x = tf.constant([[0], [10], [20], [30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [22]:
import numpy as np

print(np.arange(3))
print(np.ones((3, 3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [26]:
x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print((x+y).numpy())

x = tf.constant((np.ones((3, 3))))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

x = tf.constant(np.arange(3).reshape(3, 1))
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [27]:
a = 2
b = 3
c = tf.add(a, b)
print(c.numpy())

5


In [28]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
pow_op = tf.pow(add_op, mul_op)

print(pow_op.numpy())

15625


In [29]:
a = tf.constant(2.)
b = tf.constant(3.)
c = tf.constant(5.)

# some more operations
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print("mean = ", mean.numpy())
print("sum = ", sum.numpy())

mean =  3.3333333
sum =  10.0


In [30]:
# Matrix multiplications 1
matrix1 = tf.constant(([1., 2.], [3., 4.]))
matrix2 = tf.constant(([2., 0.], [1., 2.]))

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

# Matrix multiplications 2
gop = tf.matmul(matrix2, matrix1)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]
[[ 2.  4.]
 [ 7. 10.]]
